// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Jacob_Jia

//@version=6
strategy("ADX Moving AVG Strategy", overlay=false,  default_qty_value = 95, 
 default_qty_type = strategy.percent_of_equity)

var bool inTradeWindow = true
// ⽤户定义的回测时间窗⼜
startYear = input.int(2020, "开始年份")
startMonth = input.int(1, "开始⽉份")
startDay = input.int(1, "开始⽇")
endYear = input.int(2026, "结束年份")
endMonth = input.int(1, "结束⽉份")
endDay = input.int(1, "结束⽇")
startDate = timestamp("UTC", startYear, startMonth, startDay, 0, 0)
endDate = timestamp("UTC", endYear, endMonth, endDay, 23, 59)
inTradeWindow := (time >= startDate and time <= endDate)

// 用户选择标的
use_other_asset = input.bool(false,'是否使用其他资产来过滤长均线')
symbol_choice = input.symbol("SPX", "选择长均线标的")
selected_close = request.security(symbol_choice, '1D', close)

adx_threshold = input(26, title="ADX Threshold")
moving_avg_day = input(110, title = "Moving AVG Day")
adxlen = input(14, title="ADX Smoothing")
dilen = input(14, title="DI Length")
if_sma14_filtered = input(true, title="SMA 14 filter")
selected_ma = ta.sma(selected_close,moving_avg_day)

dirmov(len) =>
	up = ta.change(high)
	down = -ta.change(low)
	plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
	minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
	truerange = ta.rma(ta.tr, len)
	plus = fixnan(100 * ta.rma(plusDM, len) / truerange)
	minus = fixnan(100 * ta.rma(minusDM, len) / truerange)
	[plus, minus]
adx(dilen, adxlen) =>
	[plus, minus] = dirmov(dilen)
	sum = plus + minus
	adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)
adx_value = adx(dilen, adxlen)


plot(adx_value, linewidth = 2)
plot(adx_threshold,color=color.black)
sma_close_225 = ta.sma(close, moving_avg_day)
sma_close_14 = ta.sma(close, 14)

plot(sma_close_225,force_overlay = true)
var bool longCondition = false
if not if_sma14_filtered
	if use_other_asset
		longCondition := ta.crossover(adx_value, adx_threshold) and ( selected_close > selected_ma )
	else
		longCondition := ta.crossover(adx_value, adx_threshold) and ( close > sma_close_225 ) 
else
	if use_other_asset
		longCondition := ta.crossover(adx_value, adx_threshold) and ( selected_close > selected_ma ) and (sma_close_14 > sma_close_14[14])
	else
		longCondition := ta.crossover(adx_value, adx_threshold) and (close > sma_close_225) and (sma_close_14 > sma_close_14[14])

if (longCondition and inTradeWindow)
    strategy.entry("ADX", strategy.long)

var bool closeCondition = false
if use_other_asset
	closeCondition := ta.crossunder(adx_value, adx_threshold) or (selected_close < selected_ma)
else
	closeCondition := ta.crossunder(adx_value, adx_threshold) or (close < sma_close_225)

if (closeCondition and inTradeWindow)
    strategy.close("ADX",immediately = true)